[WIP} Complete set of riscvace intrinsics for Clang
fb3p/llvm-project-andes pull request #8
Opened 2020-08-29 22:51 UTC by protonu

2020-08-31 20:26 UTC, opti-mix commented on clang/lib/Headers/riscvaceintrin.h
> +static inline void __attribute__((always_inline)) opt_enable_ace() {
Question: Are you using `opt_` to distinguish it from the original ACE functions? Is it the most convenient way? Do we expect this header and the usual ACE header with inline assembly to ever be used together?

Related question, would using different C++ namespaces, but same function names solve the issue? The namespace could be used inside this header or maybe in the C++ code which includes this header like

```c++
namespace riscv_ace_intrinsics {
#include "riscvaceintrin.h"
}
```

Even if we stay with a prefix as a way to disambiguate, is `opt_` the most obvious prefix? What does it mean: Optimized? Maybe it should be something more reasonable, e.g. `fbia` or something else?

2020-08-31 20:53 UTC, protonu commented on clang/lib/Headers/riscvaceintrin.h
> +static inline void __attribute__((always_inline)) opt_enable_ace() {
Adding the opt_ was temporary. It was to let @SameerAsal ( and maybe me as well) test instructions and debugs them. For this reason, for the very near future we may need to use both ace_user.h and this header. Once we are confident, we can remove ace_user.h. I am happy to use namespaces or a different prefix.

2020-09-08 17:53 UTC, SameerAsal commented
Thanks @protonu  for this, I think this is a good diff just needs some polishing:

1) can we autogenerate some tests on the Clang side (extend the one you have) so that we can run all of them and make sure we don't have extra blockers (like the immediate problem we have). 

2) can we find a clean location to add the script you used to generate in this repo?

2020-09-09 23:01 UTC, protonu commented
> Thanks @protonu for this, I think this is a good diff just needs some polishing:
> 
> 1. can we autogenerate some tests on the Clang side (extend the one you have) so that we can run all of them and make sure we don't have extra blockers (like the immediate problem we have).
I added (auto generated) tests for the instructions.

> 2. can we find a clean location to add the script you used to generate in this repo?
I think this is the only TODO left for this PR. I'll clean up the script and add it in the PR.

> 3. there is so many commits in the diff, can we combine them and update the description? I use git-up on Mac to combine commits and update messages, I think it will be useful for you.
I actually prefer the multiple commits for now. I'll squash them into one, once I think it's ready. I'll update the message.

Thanks for the comment, please find my replies inline.

2020-09-10 00:14 UTC, opti-mix reviewed
@protonu Looks pretty good now!

Do you plan to include your script for auto-generation of headers into this PR or a separate PR? After all, we'd like to be able to re-generate all this if needed.

2020-09-10 00:14 UTC, opti-mix commented on clang/lib/CodeGen/CGBuiltin.cpp
> +      Function *F = CGM.getIntrinsic(Intrinsic::RISCVIntrinsics::riscv_rd64_din_addr, {ConvertType(E->getType())});
So, does BI__builtin_rd64_din_addr need a special casing here? It cannot use the macro? Maybe add a comment in the source code explaining why.

2020-09-10 00:14 UTC, opti-mix commented on clang/lib/Headers/riscvaceintrin.h
> +case 0: {*data = __builtin_rd_icount_fmask(0); break;}
Nit: It doesn't matter much, but maybe some macros could be used to make it look nicer? Probably don't need it for the first cut. Could be a follow-up low-pri improvement.

2020-09-10 00:14 UTC, opti-mix commented on clang/lib/Headers/riscvaceintrin.h
> +default: {
Do we even need the default? Shouldn't it assert in case if none of the above were marched?

2020-09-10 00:14 UTC, opti-mix commented on clang/test/CodeGen/riscv-ace-builtins.c
> +
This is very cool!

Question: Do I understand correctly that these tests would not work without the switch-trick?

2020-09-10 00:14 UTC, opti-mix commented on clang/lib/CodeGen/CGBuiltin.cpp
> +    //RISCV_EMIT_INTRINSIC(rd64_din_addr,
Should this commented out code be removed?

2020-09-10 00:17 UTC, protonu commented on clang/lib/Headers/riscvaceintrin.h
> +case 0: {*data = __builtin_rd_icount_fmask(0); break;}
Yes, I'd prefer to do this with functions.

2020-09-10 00:18 UTC, protonu commented on clang/lib/CodeGen/CGBuiltin.cpp
> +      Function *F = CGM.getIntrinsic(Intrinsic::RISCVIntrinsics::riscv_rd64_din_addr, {ConvertType(E->getType())});
hmm, I missed this. I'll take it out. It should all be autogenerated.

2020-09-10 00:18 UTC, protonu commented on clang/lib/CodeGen/CGBuiltin.cpp
> +    //RISCV_EMIT_INTRINSIC(rd64_din_addr,
Yes. I missed this. It should be all autogenerated. Thanks for the catch.

2020-09-10 00:19 UTC, protonu commented
> @protonu Looks pretty good now!
> 
> Do you plan to include your script for auto-generation of headers into this PR or a separate PR? After all, we'd like to be able to re-generate all this if needed.



> @protonu Looks pretty good now!
> 
> Do you plan to include your script for auto-generation of headers into this PR or a separate PR? After all, we'd like to be able to re-generate all this if needed.

Yes, as mentioned in the comment earlier.

2020-09-10 00:30 UTC, protonu commented on clang/test/CodeGen/riscv-ace-builtins.c
> +
yes, that's right.

2020-09-10 00:36 UTC, protonu commented on clang/lib/CodeGen/CGBuiltin.cpp
> +      Function *F = CGM.getIntrinsic(Intrinsic::RISCVIntrinsics::riscv_rd64_din_addr, {ConvertType(E->getType())});
To be more precise, I meant,  it doesn't need special handling. This was code left over from debugging, which I missed. Thanks for the catch.

2020-09-10 03:39 UTC, SameerAsal commented on clang/test/CodeGen/riscv-ace-builtins.c
> +void test(unsigned size, char acc) {
Is this the only test we can gen in a for loop? or can we generate for loops for the rest of the intrinsics to test hoisting? should we put it in a different file?

2020-09-10 03:42 UTC, protonu commented on clang/test/CodeGen/riscv-ace-builtins.c
> +void test(unsigned size, char acc) {
The test with a loop was not autogenerate. I don't generate tests with loops as yet. 
Yes, I plan on keeping it as a separate test.

2020-09-10 04:14 UTC, protonu commented on clang/test/CodeGen/riscv-ace-builtins.c
> +void test(unsigned size, char acc) {
@SameerAsal  can you take a look at the file with test loops. I don't want to add FileCheck to it.
TODO: polish up the python script so I don't forget what it does in a month :)

2020-09-10 16:03 UTC, opti-mix commented on clang/test/CodeGen/riscv-ace-loop-builtins.c
> +	const trn_zero_offset_t din;
Nit: din is a const, but it is not initialized.  A see a number of examples in this auto-generated file, where we don't initialize the variable/const, but use it. Could it result in some undefined behavior or something like that? Maybe we should initialize them with an unknown value e.g. passed as a parameter into a function?

2020-09-10 16:33 UTC, opti-mix reviewed
@protonu Thanks for adding the Python script for auto-generating intrinsics. It is really small! Nice!

I added some stylistic comments about the script, mostly about documentation and comments or string formatting. But this is all minor.

Also there is one comment about undefined values in the generated tests.

2020-09-10 16:33 UTC, opti-mix commented on llvm/utils/fbia_riscvace_ace_user_processor.py
> +    for index, line in enumerate(lines):
Could you add some comments here about the expected structure of the file. Like, 
- the file is expected to consist of the following section in exactly this order:... 
- The beginning of section X is identified by detecting Y....
- Each function definition is expected to have the following format...

Also add some high-level comments before if-statements, e.g. we don't convert multi-instruction functions into intrinsics, because .... and so on.

The reason for adding these comments is two-fold:
- Just documenting and making it easier to understand and later to modify
- Explicitly stating the input format we expect. This is for the case it changes later for some reason and we need to adjust.

2020-09-10 16:33 UTC, opti-mix commented on llvm/utils/fbia_riscvace_ace_user_processor.py
> +                        print("\t" + outputs + " = " + instr + args + ";")
Nit: You create complex string in Python in a very C++ way ;-) Python provides some more convenient means, described e.g. here: https://realpython.com/python-formatted-output/

It is usually easier to understand and easier to write.

2020-09-10 16:33 UTC, opti-mix commented on llvm/utils/fbia_riscvace_ace_user_processor.py
> +def gen_codegen_function():
Can you add short comments for each function describing what it does? Also, if it makes any assumptions about the structure of something, maybe briefly describe them in the comments.

2020-09-10 16:33 UTC, opti-mix commented on llvm/utils/fbia_riscvace_ace_user_processor.py
> +        intrisics_to_test.append((new_name, func_call_args, func_arg_types, immediates, raw_instr))
Could you describe the structure of each saved intrisics_to_test item in the comment for intrisics_to_test?

Nit: would it be more robust/understandable if items would be maps? Like

```
{ 'name' : new_name, 'args' : func_call_args, ... 
}
```

Maybe even a small class with these fields could be defined? It is really a nit. I'm just a bit concerned we rely too much on positional arguments and their order. But the script is so small, that it is probably not a real concern.

2020-09-10 16:37 UTC, protonu commented on llvm/utils/fbia_riscvace_ace_user_processor.py
> +    for index, line in enumerate(lines):
Thanks for the feedback, as per the comment above this script is a WIP. I'll address your comments in a following commit

2020-09-10 16:40 UTC, opti-mix commented on llvm/utils/fbia_riscvace_ace_user_processor.py
> +    for index, line in enumerate(lines):
Thanks! Overall, the PR looks really good now! I think it is almost ready to be landed after some minor polishing.

2020-09-10 17:32 UTC, SameerAsal commented on clang/test/CodeGen/riscv-ace-builtins.c
> +void test(unsigned size, char acc) {
Just looked at clang/test/CodeGen/riscv-ace-loop-builtins.c, looks OK to me :)

2020-09-11 17:21 UTC, SameerAsal commented on clang/lib/Headers/riscvaceintrin.h
> +opt_ace_rd_icount_fmask(const unsigned int idx, unsigned long long* data) {
when I look at RISCVInstrInfoACE.td the definition for this instructions looks like:
```
def rd_icount_fmask : RVACEInst<
    (outs GPR:$_data),
    (**ins uimm2:$_idx)**,
    [],
    "rd_icount_fmask", "$_idx, $_data"> 
```

idx here has two bits so the range for the switch should be 4, why are we doing 15 here? I wonder if we have a second place in the code where this is listed as having a length of 4??

2020-09-11 17:30 UTC, protonu commented on clang/lib/Headers/riscvaceintrin.h
> +opt_ace_rd_icount_fmask(const unsigned int idx, unsigned long long* data) {
That's interesting. I had the test case:
void func_opt_ace_rd_icount_fmask(unsigned long long*  data) {
	const unsigned int  idx = 15;
	// CHECK: llvm.riscv.rd.icount.fmask
	opt_ace_rd_icount_fmask(idx, data);
}

And this generated asm:
.type	func_opt_ace_rd_icount_fmask,@function
func_opt_ace_rd_icount_fmask:           # @func_opt_ace_rd_icount_fmask
# %bb.0:                                # %entry
	rd_icount_fmask	15, a1
	sd	a1, 0(a0)
	ret

2020-09-12 00:36 UTC, SameerAsal requested changes

2020-09-12 00:36 UTC, SameerAsal commented on clang/test/CodeGen/riscv-ace-builtins.c
> +	const unsigned int  ba = 0;
no check here

2020-09-12 00:36 UTC, SameerAsal commented on clang/test/CodeGen/riscv-ace-builtins.c
> +	const din_broadcast_idx  idx = 0;
No check.
also, this is strange, this intrinsic is wr64_din_broadcast not wr_*

2020-09-12 00:36 UTC, SameerAsal commented on clang/test/CodeGen/riscv-ace-builtins.c
> +	const din_cb_id_idx  idx = 0;
same problem. not sure why this is wr instead of wr_64!

2020-09-12 00:36 UTC, SameerAsal commented on clang/test/CodeGen/riscv-ace-builtins.c
> +	const din_cb_id_idx  idx = 0;
I think you are taking the name of the intrinsic from the name of the function in ace_user.h. It should be taken from the instruction mnemonic

2020-09-14 22:48 UTC, SameerAsal commented
LGTM with one small comment:

Lets just add a check to the cal of the llvm intrinsic in test/CodeGen/riscv-ace-builtins.c. so instead:
	// CHECK: llvm.riscv.rd64.dcn.zero.offset.b
we should have:
	// CHECK: call .* llvm.riscv.rd64.dcn.zero.offset.b

2020-09-16 00:27 UTC, merged